package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActivity<M extends BaseActivity<M>> extends Model<M> implements IBean {

	public void setActivityId(java.lang.Integer activityId) {
		set("activity_id", activityId);
	}

	public java.lang.Integer getActivityId() {
		return get("activity_id");
	}

	public void setActivityName(java.lang.String activityName) {
		set("activity_name", activityName);
	}

	public java.lang.String getActivityName() {
		return get("activity_name");
	}

	public void setActivityMark(java.lang.String activityMark) {
		set("activity_mark", activityMark);
	}

	public java.lang.String getActivityMark() {
		return get("activity_mark");
	}

	public void setActivitySort(java.lang.Integer activitySort) {
		set("activity_sort", activitySort);
	}

	public java.lang.Integer getActivitySort() {
		return get("activity_sort");
	}

	public void setActivityThumbImage(java.lang.String activityThumbImage) {
		set("activity_thumb_image", activityThumbImage);
	}

	public java.lang.String getActivityThumbImage() {
		return get("activity_thumb_image");
	}

	public void setActivityImage(java.lang.String activityImage) {
		set("activity_image", activityImage);
	}

	public java.lang.String getActivityImage() {
		return get("activity_image");
	}

	public void setIndexShow(java.lang.Integer indexShow) {
		set("index_show", indexShow);
	}

	public java.lang.Integer getIndexShow() {
		return get("index_show");
	}

	public void setActivityStatus(java.lang.String activityStatus) {
		set("activity_status", activityStatus);
	}

	public java.lang.String getActivityStatus() {
		return get("activity_status");
	}

	public void setJoinUsers(java.lang.Integer joinUsers) {
		set("join_users", joinUsers);
	}

	public java.lang.Integer getJoinUsers() {
		return get("join_users");
	}

	public void setDeleteFlag(java.lang.Integer deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Integer getDeleteFlag() {
		return get("delete_flag");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}

	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public void setActivityAddress(java.lang.String activityAddress) {
		set("activity_address", activityAddress);
	}

	public java.lang.String getActivityAddress() {
		return get("activity_address");
	}

}
